"""Phase 7: model registry + model cards.

Aggregates every LoRA the studio knows about - trained runs, merges, and
loose .safetensors discovered in lora_output_dir - joined with dataset
lineage and eval scores. `lora-studio card NAME` exports a markdown model
card next to the checkpoint.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from . import manifest
from .config import Project
from .util import human_bytes, now_iso


def _lora_dir(prj: Project) -> Path:
    return Path(prj.lora_output_dir
                or (Path(prj.output_base) / "LORA_OUTPUT")).expanduser()


def build_registry(prj: Project, conn) -> list[dict]:
    lora_dir = _lora_dir(prj)
    files = {p.stem: p for p in lora_dir.glob("*.safetensors")} if lora_dir.exists() else {}

    # eval averages per label
    evals: dict[str, dict] = {}
    try:
        for label, cat, n, avg in conn.execute(
            "SELECT label, category, COUNT(*), AVG(likeness) FROM evals "
            "GROUP BY label, category"
        ):
            evals.setdefault(label, {})[cat] = {
                "n": n, "avg": round(avg, 4) if avg is not None else None
            }
    except Exception:
        pass

    entries: dict[str, dict] = {}

    # trained runs
    try:
        for (name, dsv, preset, status, started, loss) in conn.execute(
            "SELECT name, dataset_version, preset, status, started_at, last_loss "
            "FROM runs ORDER BY run_id"
        ):
            matching = [p for stem, p in files.items() if stem.startswith(name)]
            entries[name] = {
                "name": name, "kind": "trained", "preset": preset,
                "dataset_version": dsv, "status": status, "created": started,
                "final_loss": loss,
                "files": [str(p) for p in sorted(matching)],
                "evals": evals.get(name, {}),
            }
    except Exception:
        pass

    # merges (meta keys merge:*)
    try:
        for (key, value) in conn.execute(
            "SELECT key, value FROM meta WHERE key LIKE 'merge:%'"
        ):
            name = key.split(":", 1)[1]
            info = json.loads(json.loads(value)) if value.startswith('"') else json.loads(value)
            entries[name] = {
                "name": name, "kind": "merged",
                "inputs": info.get("inputs", []),
                "created": info.get("created_at"),
                "files": [str(files[s]) for s in files if s == name or s.startswith(name)],
                "evals": evals.get(name, {}),
            }
    except Exception:
        pass

    # loose files not covered above
    covered = set()
    for e in entries.values():
        for f in e.get("files", []):
            covered.add(Path(f).stem)
    for stem, p in files.items():
        if not any(stem.startswith(n) for n in entries) and stem not in covered:
            entries[stem] = {
                "name": stem, "kind": "external",
                "files": [str(p)], "created": None,
                "size": human_bytes(p.stat().st_size),
                "evals": evals.get(stem, {}),
            }
    return sorted(entries.values(), key=lambda e: e["name"])


def best_likeness(entry: dict) -> Optional[float]:
    lk = entry.get("evals", {}).get("likeness", {})
    return lk.get("avg")


def model_card(prj: Project, conn, name: str) -> Optional[Path]:
    """Write MODEL_CARD_<name>.md next to the checkpoint. Returns path."""
    entry = next((e for e in build_registry(prj, conn) if e["name"] == name), None)
    if entry is None:
        return None
    lora_dir = _lora_dir(prj)

    # dataset lineage
    lineage = ""
    if entry.get("dataset_version"):
        row = conn.execute(
            "SELECT recipe_name, content_hash, image_count, val_count, built_at "
            "FROM datasets WHERE version=?", (entry["dataset_version"],),
        ).fetchone()
        if row:
            lineage = (f"| Dataset | v{entry['dataset_version']:03d} "
                       f"({row[0]}, {row[2]} train / {row[3]} val, hash {row[1]}, "
                       f"built {row[4]}) |\n")

    eval_lines = ""
    for cat, s in sorted(entry.get("evals", {}).items()):
        eval_lines += f"| Eval: {cat} | avg likeness {s['avg']} (n={s['n']}) |\n"

    inputs = ""
    for inp in entry.get("inputs", []):
        inputs += f"| Merge input | {inp['name']} @ {inp['weight']} blocks={inp['blocks']} |\n"

    files = "\n".join(f"- `{f}`" for f in entry.get("files", [])) or "- (file not located)"
    grids_dir = Path(prj.output_base) / "evals" / name
    grids = "\n".join(f"- `{g}`" for g in sorted(grids_dir.glob("GRID_*.jpg"))) \
        if grids_dir.exists() else "- (run `lora-studio matrix` to generate)"

    body = f"""# {name}

Generated by LoRA Designer Studio - {now_iso()}

| Field | Value |
|---|---|
| Kind | {entry['kind']} |
| Created | {entry.get('created') or '-'} |
| Preset | {entry.get('preset', '-')} |
| Final loss | {entry.get('final_loss', '-')} |
{lineage}{eval_lines}{inputs}
## Files

{files}

## Sample grids

{grids}

## Usage

Trigger: `{prj.trigger_token} {prj.class_word}`
Recommended weight: 0.7-0.9 (`<lora:{name}:0.85>` in Forge).
Base model: Pony Diffusion V6 XL.
"""
    out = lora_dir / f"MODEL_CARD_{name}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    return out
